Accept applicant page
Nidhushan/TimeBanking pull request #75
Opened 2024-12-09 21:01 UTC by tanaya09

## What does this pull request include?
1. UI for accept applicant

## Any outstanding issues in this pull request?
No

## Checklist

- [ ] Test locally
- [ ] Assign a reviewer
- [ ] ZenHub

2024-12-10 04:25 UTC, austinhuang0131 requested changes
should also reveal their email address for contact (this was mentioned at the end of last demo), same should also be done for the applicant

otherwise ok

2024-12-11 19:51 UTC, tanaya09 commented
I’ve addressed the requested changes:
Improved the confirmation UI for the applicant page.
Added an email display for the selected applicant. 
Please let me know if further adjustments are needed.

2024-12-11 21:06 UTC, austinhuang0131 requested changes

2024-12-11 21:06 UTC, austinhuang0131 commented on Time_Banking/Time_Banking/templates/profile_info.html
> +<p><i class="fa fa-envelope"></i> {{ user.email }}</p>
not necessary, my point was to only provide email after being accepted, but the person who applied to the service should be able to see the email of the provider on applied_services as well

2024-12-11 21:06 UTC, austinhuang0131 commented on Time_Banking/Time_Banking/templates/view_applicants.html
> +                    </p>
ok

2024-12-15 00:38 UTC, merged